development:
  adapter: postgresql
  encoding: unicode
  database: feedbackLoop_development
  pool: 5
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: feedbackLoop_test
  pool: 5
  username: shanerogers
  port: 5432